---
title: 'Calcium carbonate precipitation in Everglades periphyton: ecosystem drivers
  and consequences for a microbial process'
author: "Kristin L. Briggs"
date: "1/10/2020"
output:
  html_document: default
  pdf_document: default
---
# Research Statement
 Microbial communities drive important ecosystem functions in many terrestrial and aquatic habitats, so it is crucial to understand how environmental shifts will influence them. Periphyton mats of the Everglades are an example of a ‘foundational’ microalgal community which maintain the system’s unique biogeochemistry and habitat structure. They sequester large amounts of carbon into organic matter and calcium carbonate (CaCO3), and thereby fuel food webs, regulate carbon fluxes, and build marl soils. The widespread precipitation of CaCO3 is key to periphyton mat functioning, and more broadly, is an essential process in our geological history which built soils, sedimentary rock, along with other important functions, yet the mechanisms driving precipitation are not well understood. Periphyton is an important tool for monitoring water quality and Everglades restoration, and we know this algal community shifts to non-calcareous biofilms of reduced functionality in response to environmental shifts like prolonged hydroperiods and phosphorus enrichment. Since CaCO3 precipitation within periphyton mats is influenced by water chemistry and hydrology, it is imperative to understand how changes in these conditions will influence the system’s carbon sequestration and storage. The Everglades’ water flow is heavily managed and large-scale modifications are ongoing to restore some pre-drainage flow to improve ecosystem functioning and ecological integrity, but the impacts of these efforts are still being studied. Evaluating how CaCO3 precipitation in Everglades periphyton on the small and intermediate scale are influenced by ecosystem gradients may elucidate drivers of Everglade’s carbon budget, microbial carbonate precipitation, and help us optimize ecosystem functioning through water management. Employing manipulative experiments, field studies, analytical methods for structural and chemical analyses, and molecular techniques (e.g. SEM EDS, RNA) will allow us to answer important questions about how modified hydrology (eg. water depth, chemistry) will impact CaCO3 precipitation and periphyton functioning.  
 
# Methods  
 Depending on the data that I use, which I am still working on compiling, I would like to use some multivariable analyses which can compare the influence of hydrological and water chemistry variables on calcium carbonate precipitation in periphyton. 
 
# Data 
 As of now I'm not sure if I will have quantitative data (calcium carbonate volume, community composition data) on this yet, but I may be able to use qualitative data (periphyton type) from the field coupled with environmental metadata (water depth, pH, etc.) for some real-data analyses. Otherwise I will need to use other data. 
 

  